export default {
  centaur: {
    name: 'Centaur',
    hp: 20,
    attackPoint: 8,
    defense: 4,
    critical: 10,
    luck: 10,
    speed: 10,
    level: 1,
    id: 'Centaur',
    moveDistance: 6,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: { name: '', itemId: 0 }
  },
  valkyrie: {
    name: 'Valkyrie',
    hp: 25,
    attackPoint: 13,
    defense: 6,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    id: 'Valkyrie',
    moveDistance: 5,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: { name: '', itemId: 0 }
  },
  woodCutter: {
    name: 'WoodCutter',
    hp: 30,
    attackPoint: 10,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    id: 'WoodCutter',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: { name: '', itemId: 0 }
  },
  babyDragon: {
    name: 'BabyDragon',
    hp: 15,
    attackPoint: 7,
    defense: 5,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    id: 'BabyDragon',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: { name: '', itemId: 0 }
  },
  dragon: {
    name: 'Dragon',
    hp: 40,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    id: 'Dragon',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: { name: '', itemId: 0 }
  },
  phoenix: {
    name: 'Phoenix',
    hp: 22,
    attackPoint: 8,
    defense: 7,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    id: 'Phoenix',
    moveDistance: 6,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: { name: '', itemId: 0 }
  },
  chimera: {
    name: 'Chimera',
    hp: 25,
    attackPoint: 10,
    defense: 7,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    id: 'Chimera',
    moveDistance: 5,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: { name: '', itemId: 0 }
  }
}
