import { ICharacter } from '~/types/store'

// id は ~/pages/online/_id で初期値 + guest か host の文字列を追加され初期化される
const characters: { [characterName: string]: ICharacter } = {
  centaur: {
    name: 'Centaur',
    maxHp: 20,
    hp: 20,
    attackPoint: 8,
    defense: 4,
    critical: 10,
    luck: 10,
    speed: 10,
    level: 1,
    skill: [],
    id: 'Centaur',
    moveDistance: 10,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  alien: {
    name: 'Alien',
    maxHp: 25,
    hp: 25,
    attackPoint: 13,
    defense: 6,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Alien',
    moveDistance: 5,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  cerberus: {
    name: 'Cerberus',
    maxHp: 25,
    hp: 25,
    attackPoint: 13,
    defense: 6,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: ['sequncialAttack'],
    id: 'Cerberus',
    moveDistance: 5,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  chimera: {
    name: 'Chimera',
    maxHp: 25,
    hp: 25,
    attackPoint: 10,
    defense: 7,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Chimera',
    moveDistance: 5,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  curupira: {
    name: 'Curupira',
    maxHp: 25,
    hp: 25,
    attackPoint: 10,
    defense: 7,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: ['summonOnDead'],
    id: 'Curupira',
    moveDistance: 5,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  cyclops: {
    name: 'Cyclops',
    maxHp: 25,
    hp: 25,
    attackPoint: 10,
    defense: 7,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Cyclops',
    moveDistance: 5,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  devil: {
    name: 'Devil',
    maxHp: 25,
    hp: 25,
    attackPoint: 10,
    defense: 7,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Devil',
    moveDistance: 5,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  dinosaur: {
    name: 'Dinosaur',
    maxHp: 25,
    hp: 25,
    attackPoint: 10,
    defense: 7,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: ['predation'],
    id: 'Dinosaur',
    moveDistance: 5,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  babyDragon: {
    name: 'BabyDragon',
    maxHp: 15,
    hp: 15,
    attackPoint: 7,
    defense: 5,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'BabyDragon',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  dragon: {
    name: 'Dragon',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: ['fly'],
    id: 'Dragon',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  echidna: {
    name: 'Echidna',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Echidna',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  elf: {
    name: 'Elf',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Elf',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  fairy: {
    name: 'Fairy',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Fairy',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  frankenstein: {
    name: 'Frankenstein',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Frankenstein',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  genie: {
    name: 'Genie',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Genie',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  ghost: {
    name: 'Ghost',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Ghost',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  goblin: {
    name: 'Goblin',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Goblin',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  gryphon: {
    name: 'Gryphon',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Gryphon',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  hand: {
    name: 'Hand',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Hand',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  harpy: {
    name: 'Harpy',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: ['fly'],
    id: 'Harpy',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  hydra: {
    name: 'Hydra',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: ['sequncialAttack'],
    id: 'Hydra',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  karakasakozou: {
    name: 'Karakasakozou',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Karakasakozou',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  kraken: {
    name: 'Kraken',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Kraken',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  leprechaun: {
    name: 'Leprechaun',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Leprechaun',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  lochNessMonster: {
    name: 'LochNessMonster',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'LochNessMonster',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  madreMonte: {
    name: 'MadreMonte',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'MadreMonte',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  medusa: {
    name: 'Medusa',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Medusa',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  mermaid: {
    name: 'Mermaid',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Mermaid',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  minotaur: {
    name: 'Minotaur',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Minotaur',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  mushroom: {
    name: 'Mushroom',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Mushroom',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  narwhal: {
    name: 'Narwhal',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Narwhal',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  pegasus: {
    name: 'Pegasus',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: ['fly'],
    id: 'Pegasus',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  phoenix: {
    name: 'Phoenix',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: ['fly'],
    id: 'Phoenix',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  pinocchio: {
    name: 'Pinocchio',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Pinocchio',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  pirate: {
    name: 'Pirate',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Pirate',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  robot: {
    name: 'Robot',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Robot',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  satyr: {
    name: 'Satyr',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Satyr',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  scarecrow: {
    name: 'Scarecrow',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Scarecrow',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  troll: {
    name: 'Troll',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Troll',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  unicorn: {
    name: 'Unicorn',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Unicorn',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  valkyrie: {
    name: 'Valkyrie',
    maxHp: 25,
    hp: 25,
    attackPoint: 13,
    defense: 6,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: ['counter', 'sequncialAttack'],
    id: 'Valkyrie',
    moveDistance: 5,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  vampire: {
    name: 'Vampire',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: ['bloodSucking'],
    id: 'Vampire',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  witch: {
    name: 'Witch',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Witch',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  wizard: {
    name: 'Wizard',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Wizard',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  woodCutter: {
    name: 'WoodCutter',
    maxHp: 30,
    hp: 30,
    attackPoint: 10,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: ['summonOnDead'],
    id: 'WoodCutter',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  yeti: {
    name: 'Yeti',
    maxHp: 9999,
    hp: 9999,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    skill: [],
    id: 'Yeti',
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  },
  zombie: {
    name: 'Zombie',
    maxHp: 10,
    hp: 10,
    attackPoint: 18,
    defense: 10,
    critical: 10,
    luck: 10,
    speed: 6,
    level: 1,
    id: 'Zombie',
    skill: ['undead'],
    moveDistance: 4,
    latLng: { x: -1, y: -1 },
    lastLatLng: { x: -1, y: -1 },
    actionState: {
      name: '',
      itemId: 0,
      isEnd: false,
      interactLatLng: { x: -1, y: -1 }
    }
  }
}

export default characters
